spring.application.name=backend

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.reading.jdbc-url=${DB_PROPERTY_URL}
spring.datasource.reading.username=${DB_PROPERTY_USERNAME}
spring.datasource.reading.password=${DB_PROPERTY_PASSWORD}
spring.datasource.reading.driver-class-name=org.postgresql.Driver

spring.datasource.writing.jdbc-url=${DB_ZONING_URL}
spring.datasource.writing.username=${DB_ZONING_USERNAME}
spring.datasource.writing.password=${DB_ZONING_PASSWORD}
spring.datasource.writing.driver-class-name=org.postgresql.Driver

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

spring.jpa.database=default

server.port=${PORT:8080}