CREATE TABLE public.audit_logs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	message text NULL,
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);


CREATE TABLE public.property_zoning_updates (
	property_ref_id int8 NOT NULL,
	updated_at timestamp(6) NOT NULL,
	zoning_type varchar(255) NOT NULL,
	CONSTRAINT property_zoning_updates_pkey PRIMARY KEY (property_ref_id),
	CONSTRAINT property_zoning_updates_zoning_type_check CHECK (((zoning_type)::text = ANY ((ARRAY['Residential'::character varying, 'Commercial'::character varying, 'Industrial'::character varying, 'Planned'::character varying])::text[])))
);